# Generated by Django 5.0.3 on 2024-03-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0002_yanswer_imgfile_yquestion_imgfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yanswer',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to='yolo/answer/%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='yquestion',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to='yolo/question/%Y%m%d'),
        ),
    ]
