# Generated by Django 5.0.3 on 2024-03-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0003_alter_yanswer_imgfile_alter_yquestion_imgfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yanswer',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
